title: Shiyunc
description: <p> I studied Electrical & Systems Engineering, involving data & systems. I experienced in managing of large-scale systems development projects & using data tools for data analytics, and i enjoy helping people's to solve everyday problems using technology. </p> *https://public.tableau.com/app/profile/sylearn *https://medium.com/@shiyun-c
theme: jekyll-theme-minimal
