title: Shiyunc
description: <p> Hi! I studied Electrical & Systems Engineering, involving data & systems. I experienced in managing of large-scale data analytics & systems projects, and i enjoy applying my skills to help people to solve everyday problems. </p> *https://public.tableau.com/app/profile/sylearn *https://medium.com/@shiyun-c
theme: jekyll-theme-minimal
